apiVersion: apps/v1
kind: Deployment
metadata:
  name: gehenna-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: gehenna-backend
  template:
    metadata:
      labels:
        app: gehenna-backend
    spec:
      initContainers:
      - name: wait-for-mongo
        image: busybox
        command: ['sh', '-c', 'until nc -z mongo 27017; do echo waiting for mongo; sleep 3; done']
      containers:
      - name: gehenna-backend
        image: {{ .Values.backendImage }}
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: gehenna-config
              key: BACKEND_PORT
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: gehenna-secrets
              key: MONGO_URL
        # envFrom:
        # - configMapRef:
        #     name: gehenna-config
        # - secretRef:
        #     name: gehenna-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: gehenna-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: gehenna-backend
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP

