apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: testforall.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gehenna-frontend
              port:
                number: 8001
        - path: /db
          pathType: Prefix
          backend:
            service:
              name: mongo-express
              port:
                number: 8081
        